### ISSUE TITLE
Inquiry on Temporal-sampling Implementation

### ISSUE THREAD

**Issue by STARK-775178** [kwwcv/SSMP#2]
Hello,
I am currently working through your paper "[Semi-Supervised Class-Agnostic Motion Prediction with Pseudo Label Regeneration and BEVMix](https://github.com/kwwcv/SSMP)" and attempting to replicate the experimental setup. I couldn't find the implementation details for the "Temporal-sampling" technique mentioned in your paper, which is a crucial part of the data augmentation strategy.

Could you please point me to where this feature is implemented in the codebase, or provide guidance on how it's integrated? Your assistance would be greatly appreciated.

Thank you for your time and for sharing your research. 0.o

**Comment by kwwcv** [comment]
As the paper title highlights, the most important parts are actually "pseudo label regeneration" and "BEVMix". As for temporal-sampling(TS), we've recently observed that it results in the instability of the final performances,  so TS was removed in the codebase. I'm unable to access the original code anymore, but you could try implementing TS on your own if you're keen. I believe it would be fairly straightforward to do.
